### ISSUE TITLE
Appears not to work on ASP.NET Core 2.2

### ISSUE THREAD

**Issue by kevingates** [OdeToCode/UseNodeModules#4]
While following https://app.pluralsight.com/library/courses/aspnetcore-mvc-efcore-bootstrap-angular-web course, he recommends your tool to use the Node Modules. His video references Core 2.1. I've been using 2.2 of Core. And while I can download your tool as a dependency, it do not work in actually loading the node_modules within wwwroot in the dev environment.

**Comment by OdeToCode** [comment]
I'm not sure how you have node_modules moved into wwwroot, but the goal of this package is to avoid using wwwroot for node_modules. Perhaps the intended behavior is misunderstood.
