### ISSUE TITLE
No longer works on my v2.2 .netcoreapp 

### ISSUE THREAD

**Issue by LaVillaine** [OdeToCode/UseNodeModules#7]
I've got a v2.2 .net core app which worked fine 2/3 weeks ago with UseNodeModules version 3.0. Ran a nuget package restore today and the restore fails with the following message: 

NU1202: Package OdeToCode.UseNodeModules 3.0.0 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package OdeToCode.UseNodeModules 3.0.0 supports: netcoreapp3.0 (.NETCoreApp,Version=v3.0)

I'm wary about upgrading my whole app to netcore v3.0 as there are a few other dependencies which could be affected

**Comment by OdeToCode** [comment]
The 3.0 version has to support breaking changes in ASP.NET Core 3.0. Use the previous version for 2.x:

```
dotnet add package OdeToCode.UseNodeModules --version 1.0.6
```
